# Generated by Django 5.2.4 on 2025-07-24 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_author_alter_book_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_picture',
            new_name='profile_photo',
        ),
    ]
